version: '3.8'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /docker/minio:/data
    restart: unless-stopped
    networks:
      - default
      - external
  
  kafka1:
    container_name: kafka1
    image: djadeau/kafka:3.3.1
    build: 
      context: .
    ports:
        - "9192:9092"
        - "9193:9093"
    networks:
      #- default
      #- external
      kafka-net:
        ipv4_address: "172.180.0.11"
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: kafka2
    image: djadeau/kafka:3.3.1
    build: 
      context: .
    ports:
        - "9292:9092"
        - "9293:9093"
    networks:
      #- default
      kafka-net:
        ipv4_address: "172.180.0.12"
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: kafka3
    image: djadeau/kafka:3.3.1
    build: 
      context: .
    ports:
        - "9392:9092"
        - "9393:9093"
    networks:
      #- default
      kafka-net: 
        ipv4_address: "172.180.0.13"
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/

networks:
  kafka-net:
    ipam:
      config:
        - subnet: 172.180.0.0/16
  default:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
  external:
    driver: bridge
    internal: false